### ISSUE TITLE
Can't load imgui conflict features 

### ISSUE THREAD

**Issue by Lightnet** [jaynus/amethyst-imgui#5]
can't get the 

```
[dependencies]
amethyst-imgui = { version = "0.3.1", features = ["vulkan"] }
```

**Comment by jaynus** [comment]
This has changed now to not use features flag for backend anymore, and we inherit the feature flag by the project.

**Comment by Awpteamoose** [comment]
tl;dr you just need
```toml
[dependencies]
amethyst-imgui = "0.5.1"
```
